### PR TITLE
Flutter - Showcase - Update Groupon Card

### PR DESCRIPTION
**Pull request by GomezMimo**
## **Subscribe form page**
Update Groupon Card

## Ticket
https://buganizer.corp.google.com/issues/144492704

## Staging link
https://huge-flutter-dev-staging.firebaseapp.com/showcase

## Screenshot image
image

### CODE REVIEW

**Review by OmarGM2294 — APPROVED** [review]
LGTM

**Comment by johnatan-garcia** [comment]
Same as the other PR, you can compress this stuff better:

image

**Comment by GomezMimo** [comment]
@johnatan-garcia Images optimized, thanks for your input.

**Review by johnatan-garcia — APPROVED** [review]
Thanks!

**Pull request merged**
